### ISSUE TITLE
fm库提问

### ISSUE THREAD

**Issue by hulaba** [Wchoward/SNA_Project#1]
你好，请问process_weather中的import fm语句中的fm是什么库？

**Comment by Wchoward** [comment]
一个手写的处理文件的自定义模块，已上传

**Comment by hulaba** [comment]
好的！感谢回答!同样是在process_weather中，最后保存的A.csv的out_index和in_index会比其他4个csv文件少两列，其他4个csv文件都是out_index_x,out_index_y,in_index_x,in_index_y，最后在singleLSTM中reshape时会报错

**Comment by Wchoward** [comment]
#2

**Comment by Wchoward** [comment]
> 好的！感谢回答!同样是在process_weather中，最后保存的A.csv的out_index和in_index会比其他4个csv文件少两列，其他4个csv文件都是out_index_x,out_index_y,in_index_x,in_index_y，最后在singleLSTM中reshape时会报错

见 #2

**Comment by hulaba** [comment]
> > 好的！感谢回答!同样是在process_weather中，最后保存的A.csv的out_index和in_index会比其他4个csv文件少两列，其他4个csv文件都是out_index_x,out_index_y,in_index_x,in_index_y，最后在singleLSTM中reshape时会报错
> 
> 见 #2

好的，谢谢您！
