### ISSUE TITLE
process_weather migration bug

### ISSUE THREAD

**Issue by hulaba** [Wchoward/SNA_Project#2]
同样是在process_weather中，最后保存的A.csv的out_index和in_index会比其他4个csv文件少两列，其他4个csv文件都是out_index_x，out_index_y，in_index_x，in_index_y，最后在singleLSTM中reshape时会报错，感觉应该是A = merge_mig(A,0)这句造成的，

**Comment by hulaba** [comment]
另外，在singleLSTM中将结果写入csv文件时会报错：ValueError: Length of values does not match length of index，由于还是刚看您的代码，所以不是很熟悉，需要麻烦您帮忙解释一下，谢谢！

**Comment by Wchoward** [comment]
> 同样是在process_weather中，最后保存的A.csv的out_index和in_index会比其他4个csv文件少两列，其他4个csv文件都是out_index_x，out_index_y，in_index_x，in_index_y，最后在singleLSTM中reshape时会报错，感觉应该是A = merge_mig(A,0)这句造成的，

https://github.com/Wchoward/SNA_Project/blob/1676aac951187d783af9b7088d23fed9e7f09ed5/process_weather.ipynb#L127-L130 此处应为 B C D E的 merge_mig内的参数应分别为B C D E

**Comment by Wchoward** [comment]
> 另外，在singleLSTM中将结果写入csv文件时会报错：ValueError: Length of values does not match length of index，由于还是刚看您的代码，所以不是很熟悉，需要麻烦您帮忙解释一下，谢谢！

写入csv前 读取了baseline生成的csv文件，并做了日期及infection的值替换

**Comment by hulaba** [comment]
> > 另外，在单个LSTM中将结果写入csv文件时会报错：ValueError：值的长度与索引的长度不匹配，由于还是刚看您的代码，所以不是很熟悉，需要麻烦您帮忙解释一下，谢谢！
> 
> 写入csv前读取了baseline生成的csv文件，并做了日期及infection的值替换

是的，这个值替换的操作看懂了，但是没想明白长度不匹配的问题

**Comment by Wchoward** [comment]
建议检查一下submission文件是否包含了header，可以输出一下submission 及 infection的长度看一下

**Comment by hulaba** [comment]
> > > 另外，在一部分LSTM中将结果写入csv文件时会报错：ValueError：值的长度与索引的长度不匹配，由于还是刚看您的代码，所以不是很熟悉，需要麻烦您帮忙解释一下，谢谢！
> > 
> > 
> > 写入csv前读取了baseline生成的csv文件，并做了日期及infection的值替换
> 
> 是的，这个值替换的操作看懂了，但是没想明白长度不匹配的问题

刚刚问题解决了，header那里我改错了，所以不匹配，非常谢谢您的回答！祝您晚安

**Comment by hulaba** [comment]
> 建议检查一下submission文件是否包含标题，可以输出一下submission及infection的长度看一下



> 建议检查一下submission文件是否包含标题，可以输出一下submission及infection的长度看一下

刚刚问题解决了，header那里我改错了，所以不匹配，非常谢谢您的回答！祝您晚安
