### ISSUE TITLE
process_density question

### ISSUE THREAD

**Issue by hulaba** [Wchoward/SNA_Project#3]
你好，请问process_density中最后一段代码：
for i in range(result1.shape[0]):
    if result1.loc[i, 'region_id'] == -1:
        grid = result1.loc[i,['grid_x','grid_y']].values
        result1.loc[i,'region_id'] = set_region_id(grid)
result1
这个是求什么东西呢？A(1).CSV的是做什么用的呢？

**Comment by Wchoward** [comment]
A(1) B(1)等是抽取出region特征后的结果
https://github.com/Wchoward/SNA_Project/blob/f07dccb46ea38aebe02c2aa6c0a420a338231f89/process_density.ipynb#L281-L285
是对于没有对应上经纬度的行，通过计算他们的经纬度到各区域中心点的距离大小，分配给他们最近的region，因为计算量太大，没有采用，没有删除此代码，只是留着做记录

**Comment by hulaba** [comment]
> A(1) B(1)等是抽取出region特征后的结果
> https://github.com/Wchoward/SNA_Project/blob/f07dccb46ea38aebe02c2aa6c0a420a338231f89/process_density.ipynb#L281-L285
> 
> 
> 是对于没有对应上经纬度的行，通过计算他们的经纬度到各区域中心点的距离大小，分配给他们最近的region，因为计算量太大，没有采用，没有删除此代码，只是留着做记录

原来是这样，谢谢回答！
